apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  namespace: test-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: netflix
      namespace: test-app
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{ toYaml .Values.resources | nindent 14 }}
